FLOW-8549: Add companyMarket request param to fetch predefined portals
FLOWFACT/ff-api-services pull request #102
Opened 2020-11-05 13:10 UTC by brachfal

Add optional companyMarket request parameter to filter predefined portals

2020-11-06 07:42 UTC, ffjanhoeck requested changes

2020-11-06 07:42 UTC, ffjanhoeck commented on src/service/PortalManagementService/PortalController.ts
> +    async fetchPredefinedPortals(companyMarket: string) {
You are changing a existing API here. Please also increase the major version in the package.json :) 
Is that parameter always required ? If not, please add a optional indicator behind companyMarket

2020-11-06 08:48 UTC, brachfal commented on src/service/PortalManagementService/PortalController.ts
> +    async fetchPredefinedPortals(companyMarket: string) {
fixed :)

2020-11-06 13:56 UTC, ffjanhoeck commented on package.json
> +    "version": "29.0.0-SNAPSHOT",
Since you now have added the optional questionmark indicator, you do not need to increase the version anyloger, because the API is now downward compatible :)

2020-11-09 07:19 UTC, ffjanhoeck approved these changes

2020-11-09 07:19 UTC, merged