NO-JIRA: refactor user service
FLOWFACT/ff-api-services pull request #144
Opened 2021-02-04 13:13 UTC by rhoffmann

- add optional version param to ApiClient constructor
- refactor and type UserService

2021-02-05 13:46 UTC, ffjanhoeck requested changes

2021-02-05 13:46 UTC, ffjanhoeck commented on src/service/UserService/v2/index.ts
> +export const UserServiceInstanceV2 = new UserServiceV2();
Bitte nenne den vs/UsersController einfach zu UsersV2Controller um und registriere diesen auch in der anderen index.ts Datei. Dann mittels this.usersV2 = new UsersV2Controller.
Danach bitte diese index hier löschen und den v2 Ordner :)

2021-02-05 13:47 UTC, ffoliversaternus approved these changes

2021-02-08 06:02 UTC, ffjanhoeck approved these changes

2021-02-08 14:01 UTC, merged