FLOW-8791: enable etags again (using browsers CacheStorage)
FLOWFACT/ff-api-services pull request #146
Opened 2021-02-05 08:48 UTC by samuel-bach

2021-02-05 14:00 UTC, rhoffmann commented on src/http/cache/cache.ts
> +        if (!item) return;
please always use brackets (see https://flowfact.atlassian.net/wiki/spaces/RD/pages/2301231140/4.+Code+guidelines)

2021-02-05 14:02 UTC, rhoffmann commented on src/http/cache/cache.ts
> +            return (await apiCache()).put(url, new Response(body, { headers }))
i think you don't need to await here as well, as apiCache() already does await

2021-02-05 14:09 UTC, rhoffmann commented on src/http/cache/cache.ts
> +    while (header.value) {
more ideomatic would be a `for ... of` or 
```
const result: HeaderObject = Object.keys(headers).reduce((result, header) => {
  result[header] = headers.get(header) || "";
  return result;
}, {})`
```

2021-02-05 14:11 UTC, rhoffmann commented on src/http/cache/index.ts
> +        const cachedEtag = (await getCachedItem(config))?.headers?.etag;
you could use `getCachedItem` here without the await when you move the await logic inside getCachedItem, makes is just look nicer :)

2021-02-05 14:11 UTC, rhoffmann commented on src/http/cache/index.ts
> +function getCachedItem(config: AxiosRequestConfig) {
async -> await, see above

2021-02-05 14:12 UTC, rhoffmann commented on src/http/cache/cache.ts
> +    async reset() {
no need for async here

2021-02-05 14:13 UTC, rhoffmann commented on src/http/cache/cache.ts
> +        return caches.delete(cacheName)
await caches.delete?

2021-02-05 14:13 UTC, rhoffmann reviewed
some remarks considering async/await

2021-02-05 16:07 UTC, rhoffmann commented on src/http/cache/cache.ts
> +    while (header.value) {
bzw. [...headers.entries()].

2021-02-09 15:06 UTC, ffjanhoeck requested changes

2021-02-09 15:06 UTC, ffjanhoeck commented on src/http/cache/cache.ts
> +        } catch(e) {
Bitte ausgeschriebene Variablen verwenden.
https://flowfact.atlassian.net/wiki/spaces/RD/pages/2301231140/4.+Code+guidelines

2021-02-09 15:06 UTC, ffjanhoeck commented on src/http/cache/cache.ts
> +    return headers["content-type"]?.includes("-stream") // e.g. application/octet-stream
BItte keine doppelten Anführungszeichen verwenden

2021-02-09 15:06 UTC, ffjanhoeck commented on src/http/cache/cache.ts
> +    return headers["content-type"]?.includes("-stream") // e.g. application/octet-stream
Prettier müsste dies eigentlich alles übernehmen :)

2021-02-09 15:06 UTC, ffjanhoeck commented on src/http/cache/cache.ts
> +    return await caches.open(cacheName)
Ich glaube `caches` existiert nicht in NodeJS. Kannst du das bitte ein mal überprüfen?
ff-api-services soll auch von nodejs services eingesetzt werden

2021-02-09 15:06 UTC, ffjanhoeck commented on src/http/cache/cache.ts
> +    return await caches.open(cacheName)
Deswegen haben wir `store` verwendet, weil es dies selber handelt

2021-02-09 16:31 UTC, samuel-bach commented on src/http/cache/cache.ts
> +    return await caches.open(cacheName)
Ist in Node leider nicht vorhanden. Hab eingebaut das axios nur cached wenn `caches` auch verfügbar ist.
Können wir erstmal damit leben das Node kein bandwidth caching hat?

2021-02-10 09:27 UTC, ffjanhoeck commented on src/http/cache/cache.ts
> +    return await caches.open(cacheName)
Ja na klar, funktioniert da sowieso meines Wissens nach nicht ;)

2021-02-11 15:42 UTC, ffjanhoeck approved these changes

2021-02-16 14:43 UTC, merged