Refactor LambdaProxyService
FLOWFACT/ff-api-services pull request #158
Opened 2021-03-03 11:50 UTC by ffvietpham

Implementation of activity report v2 requests and refactoring of the LambdaProxyService to the new structure.

2021-03-03 11:55 UTC, ffjanhoeck requested changes
Because that is a breaking change, you should increase the version in the package.json

2021-03-03 11:55 UTC, ffjanhoeck commented on src/util/EnvironmentManagement.ts
> +    }
This is too specific and should not be in this file here

2021-03-03 11:56 UTC, ffvietpham commented on src/util/EnvironmentManagement.ts
> +            return 'https://latest-development-activity-report-v2-cloud.fe.flowfact-dev.cloud';
This will be changed later, after we get the url for production configured

2021-03-03 11:56 UTC, ffjanhoeck commented
Please also prettify your code!

2021-03-03 11:59 UTC, rhoffmann commented on src/util/EnvironmentManagement.ts
> +            return 'https://latest-development-activity-report-v2-cloud.fe.flowfact-dev.cloud';
in API Mapping there is a LambdaAPIService class,, where you can use a `forceUrl` parameter for this case, i think

2021-03-29 13:14 UTC, fftobiashoffmann commented on src/service/ActivityReportService/ActivityReportV2Controller.ts
> +    async prepareEmailBody(links: ActivityReportLinkType[], message: string): Promise<ApiResponse<LambdaServiceResponse>> {
can you add comments above

2021-03-29 13:15 UTC, fftobiashoffmann commented on src/service/ImporterRecordLogService/ImporterRecordLogController.ts
> +        return this.invokeApiWithErrorHandling('/ff-importer-v2-record-log-s3-directory-entries', 'GET');
can you add the type here?

2021-03-29 13:15 UTC, fftobiashoffmann commented on src/service/ImporterRecordLogService/ImporterRecordLogController.ts
> +        return this.invokeApiWithErrorHandling('/ff-importer-v2-record-log-s3-directory-content', 'POST', { table });
and here

2021-03-29 13:31 UTC, ffvietpham commented on src/service/ActivityReportService/ActivityReportV2Controller.ts
> +    async prepareEmailBody(links: ActivityReportLinkType[], message: string): Promise<ApiResponse<LambdaServiceResponse>> {
@fftobiashoffmann , is done

2021-03-29 13:32 UTC, ffvietpham commented on src/service/ImporterRecordLogService/ImporterRecordLogController.ts
> +        return this.invokeApiWithErrorHandling('/ff-importer-v2-record-log-s3-directory-entries', 'GET');
Hi @fftobiashoffmann , we have just migrated this service to the new structure and don't maintain it. So we don't know about the type of the response

2021-03-29 13:32 UTC, ffvietpham commented on src/service/ImporterRecordLogService/ImporterRecordLogController.ts
> +        return this.invokeApiWithErrorHandling('/ff-importer-v2-record-log-s3-directory-content', 'POST', { table });
Hi @fftobiashoffmann , we have just migrated this service to the new structure and don't maintain it. So we don't know about the type of the response

2021-03-30 11:51 UTC, fftobiashoffmann approved these changes

2021-03-30 13:02 UTC, merged