feat FLOW-11059 User additional data and Additional fields Config
FLOWFACT/ff-api-services pull request #179
Opened 2021-03-30 12:03 UTC by JakubJagosz

2021-04-01 08:32 UTC, ffjanhoeck requested changes

2021-04-01 08:32 UTC, ffjanhoeck commented on src/service/UserService/UserService.Types.ts
> +}
Your type in AdditionalField can also be `ADDRESS`, because you defined type as `SchemaV2FieldType`.
But a address is not a string, but you defined `value: string;`. Is that right ?

2021-04-01 08:32 UTC, ffjanhoeck commented on src/service/UserService/UserService.Types.ts
> +    type: SchemaV2FieldType;
Doesn't it make sense to also add `subType` ?

2021-04-06 08:32 UTC, JakubJagosz commented on src/service/UserService/UserService.Types.ts
> +}
Yes it was a mistake to use SchemaV2FieldType. I created separate enum for `AdditionalFieldType`. So far we're required to accept only 'TEXT' (might be extended in the future)

2021-04-06 08:34 UTC, JakubJagosz commented on src/service/UserService/UserService.Types.ts
> +    type: SchemaV2FieldType;
We're now using separate field type related to additional data only - not related to SchemaV2FieldType

2021-04-06 11:28 UTC, sizmamani approved these changes

2021-04-06 19:33 UTC, ffjanhoeck approved these changes

2021-04-06 19:33 UTC, merged