FLOW-13277: Change GeoInformationValue
FLOWFACT/ff-api-services pull request #223
Opened 2021-06-17 11:22 UTC by kamilachoroszucha

2021-06-17 12:50 UTC, Paul-Meltzer requested changes

2021-06-17 12:50 UTC, Paul-Meltzer commented on src/service/GeoInformationService/GeoInformationService.Types.ts
> +        coordinates: Array<any>;
Please avoid the `any`. As you told in Slack: We know the structure, so we can create a type for that.

2021-06-18 09:35 UTC, Paul-Meltzer approved these changes

2021-06-18 09:35 UTC, merged

2021-06-18 09:43 UTC, nawrotw commented on src/service/GeoInformationService/GeoInformationService.Types.ts
> +    export type Point = [number, number];
GeoPoint will be more accurate name imao.

2021-06-18 09:48 UTC, Paul-Meltzer commented on src/service/GeoInformationService/GeoInformationService.Types.ts
> +    export type Point = [number, number];
Sorry, I already merged it. But I also think that points except 3d points, you have always two coordinates, not only for geo!?

2021-06-18 10:17 UTC, nawrotw commented on src/service/GeoInformationService/GeoInformationService.Types.ts
> +    export type Point = [number, number];
Okey, what I was thinking that we don't have any info here which number is latitude and which is longitude.
But Point or GeoPoint don't solve this problem :-( 
So you argumentation for Point is fine for me

The problem here is that we have [longitude, latitude] order, but eg GoogleApi uses latitude, longitude order so I was thinking that we might express this order some how in types, to make them clear, what do you think?
Because it is not obvious which is which.
Maybe something like this:

`
export type Latitude = number;
export type Longitude = number;
export type GeoPoint = [Longitude, Latitude];
`

2021-06-18 11:16 UTC, Paul-Meltzer commented on src/service/GeoInformationService/GeoInformationService.Types.ts
> +    export type Point = [number, number];
I like this idea. So feel free to change it or ask @kamilachoroszucha to do so.