FLOW-13887 Add endpoint to synchronize Mailchimp contacts
FLOWFACT/ff-api-services pull request #251
Opened 2021-07-09 14:16 UTC by l-pawliczak

2021-07-09 16:14 UTC, ncmbch requested changes

2021-07-09 16:14 UTC, ncmbch commented on src/service/MailchimpSyncIntegrationService/MailchimpController.ts
> +        return this.invokeApiWithErrorHandling(`/publish`, "POST");
What about the <type> ?

2021-07-09 16:15 UTC, ncmbch commented on src/service/MailchimpSyncIntegrationService/MailchimpController.ts
> +        return this.invokeApiWithErrorHandling(`/publish`, "POST");
type*

2021-07-09 16:30 UTC, ffjanhoeck commented on src/service/MailchimpSyncIntegrationService/MailchimpController.ts
> +        return this.invokeApiWithErrorHandling(`/publish`, "POST");
And wrong

2021-07-09 17:05 UTC, l-pawliczak commented on src/service/MailchimpSyncIntegrationService/MailchimpController.ts
> +        return this.invokeApiWithErrorHandling(`/publish`, "POST");
Added void type and changed " to '

2021-07-12 08:39 UTC, JakubJagosz commented on src/service/MailchimpSyncIntegrationService/MailchimpService.Types.ts
>      export enum SyncDirection {
Please add type 'BOTH' here

2021-07-12 12:26 UTC, ffjanhoeck approved these changes

2021-07-12 12:26 UTC, merged