Flow 10616 move api calls
FLOWFACT/ff-api-services pull request #262
Opened 2021-07-21 21:28 UTC by aarostegui

## Summary
Getting rid of all the axios calls on the platform-apps iex v2

<br />

## Links
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-10616

<br />

2021-07-22 05:08 UTC, ffjanhoeck requested changes
You never export your services in the index.ts. 
Is this tested ?

2021-07-22 05:08 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2S3Service/InteractiveExposeV2S3Controller.ts
> +    getGlobalTemplateRepository() {
We do not prefix any method in ff-api-services with `get`. Everything is a `fetch` because of fetching data

```suggestion
    fetchGlobalTemplateRepository() {
```

2021-07-22 05:08 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2S3Service/InteractiveExposeV2S3Controller.ts
> +        return this.invokeApiWithErrorHandling<Entity[]>('/global/template-repo.json', 'GET');
Are you sure that this function returns a `Entity` Array ? Sounds wrong :D

2021-07-22 05:08 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2S3Service/InteractiveExposeV2S3Service.Types.ts
> +}
Not needed, when there are not types

2021-07-22 05:08 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2S3Service/index.ts
> +export const InteractiveExposeV2S3ServiceInstance = new InteractiveExposeV2S3Service();
This whole `InteractiveExposeV2S3Service` is not needed in my opinion. It is part of Interactive Expose V2, so it can be included in `InteractiveExposeV2Service`. Just create a controller and access it with `s3`

2021-07-22 05:08 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Controller.ts
> +}
This is not how controllers works. Please split it into CompanySettingsController and TemplateController

2021-07-22 05:08 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
> +}
What is the difference between V1_V2 and V2_V1 ?

2021-07-22 05:08 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
> +        iexMultilanguage: boolean;
Please run prettier before committing or directly enable it in your IDE

2021-07-22 05:08 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2Service/index.ts
> +        this.iex = new InteractiveExposeV2Controller();
As I already commented: Please split the InteractiveExposeV2Controller into two Controllers and give it a better indentification name here. For example: `this.template` and `this.companySettings`

2021-07-22 11:43 UTC, aarostegui commented on src/service/InteractiveExposeV2S3Service/InteractiveExposeV2S3Controller.ts
> +    getGlobalTemplateRepository() {
Already done

2021-07-22 11:43 UTC, aarostegui commented on src/service/InteractiveExposeV2S3Service/InteractiveExposeV2S3Controller.ts
> +        return this.invokeApiWithErrorHandling<Entity[]>('/global/template-repo.json', 'GET');
Yes, this is a static json file on s3 with a list of global templates with the same topology as entities

2021-07-22 11:44 UTC, aarostegui commented on src/service/InteractiveExposeV2S3Service/InteractiveExposeV2S3Service.Types.ts
> +}
Removed

2021-07-22 11:46 UTC, aarostegui commented on src/service/InteractiveExposeV2S3Service/index.ts
> +export const InteractiveExposeV2S3ServiceInstance = new InteractiveExposeV2S3Service();
I did it this way because the mappings are different. One is a lambda and the other one is another new mapping type I created for S3. I don't think both can live together since the url construction would be problematic

2021-07-22 11:46 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Controller.ts
> +}
You're right, will change it

2021-07-22 11:49 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
> +}
Please look at https://flowfact.atlassian.net/browse/FLOW-12144.

I also added it to the PR notes.

2021-07-22 11:50 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
> +        iexMultilanguage: boolean;
👍

2021-07-22 11:51 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/index.ts
> +        this.iex = new InteractiveExposeV2Controller();
Added comments above also

2021-07-22 13:21 UTC, aarostegui commented on src/service/InteractiveExposeV2S3Service/index.ts
> +export const InteractiveExposeV2S3ServiceInstance = new InteractiveExposeV2S3Service();
Oh, actually, let me take that back. Maybe I can have the two mappings, and each controller extends of a different mapping?

2021-07-22 13:38 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Controller.ts
> +}
Done

2021-07-22 13:38 UTC, aarostegui commented on src/service/InteractiveExposeV2S3Service/index.ts
> +export const InteractiveExposeV2S3ServiceInstance = new InteractiveExposeV2S3Service();
Done

2021-07-22 13:39 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
> +        iexMultilanguage: boolean;
Done

2021-07-22 13:39 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/index.ts
> +        this.iex = new InteractiveExposeV2Controller();
Done

2021-07-23 06:13 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Controller.ts
> +    iexBlast(templateId: string, payload: InteractiveExposeV2ServiceTypes.BlastRequest) {
`sendBlast` is a better name, because `iex` is not needed as prefix, because you are already in the "iex" context here

```suggestion
    sendBlast(templateId: string, payload: InteractiveExposeV2ServiceTypes.BlastRequest) {
```

2021-07-23 06:13 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2S3Controller.ts
> +export class InteractiveExposeV2S3Controller extends APIClient {
Please name it TemplatesRepositoryController

2021-07-23 06:13 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2S3Controller.ts
> +    getGlobalTemplateRepository() {
```suggestion
    fetchGlobalTemplateRepository() {
```

2021-07-23 07:40 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Controller.ts
> +    iexBlast(templateId: string, payload: InteractiveExposeV2ServiceTypes.BlastRequest) {
Agree

2021-07-23 07:46 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2S3Controller.ts
> +export class InteractiveExposeV2S3Controller extends APIClient {
Done

2021-07-23 07:46 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2S3Controller.ts
> +    getGlobalTemplateRepository() {
Done

2021-07-23 09:13 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2Service/CompanySettingsController.ts
> +    loadExtendedSettings() {
```suggestion
    fetchExtendedSettings() {
```

2021-07-23 09:13 UTC, ffjanhoeck commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
> +}
Why did enum is also not part of InteractiveExposeV2ServiceTypes namespace ?

2021-07-23 14:26 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
> +}
I can put it there, no problem

2021-07-23 14:44 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
> +}
Done

2021-07-23 14:44 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/CompanySettingsController.ts
> +    loadExtendedSettings() {
Done

2021-07-23 14:51 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
> +}
Oh, I remember now. If I do this it's not finding the enum at runtime, it's strange:
RelogService.ts:120 TypeError: Cannot read property 'IEXModeType' of undefined
    at SettingsPageNavigation.tsx:52
    at mountMemo (react-dom.development.js:15442)
    at Object.useMemo (react-dom.development.js:15738)
    at useMemo (react.development.js:1521)
    at SettingsPageNavigation (SettingsPageNavigation.tsx:51)
    at renderWithHooks (react-dom.development.js:14803)
    at mountIndeterminateComponent (react-dom.development.js:17482)
    at beginWork (react-dom.development.js:18596)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)

2021-07-23 16:44 UTC, aarostegui commented on src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
> +}
OK, fixed

2021-07-24 08:21 UTC, ffjanhoeck approved these changes

2021-07-26 08:41 UTC, merged