FLOW-7550: Add method to IS24PublishController.ts
FLOWFACT/ff-api-services pull request #81
Opened 2020-08-25 11:39 UTC by fftobiashoffmann

2020-08-25 13:32 UTC, ffgregormueller commented on src/service/IS24PublishService/IS24PublishController.ts
> +    async fetchReport(estateId: string, startDate: any, toDate: any) {
Richtige Typen (number?) wären hier super!

2020-08-25 13:32 UTC, ffgregormueller commented on src/service/IS24PublishService/IS24PublishController.ts
> +        return await this.invokeApiWithErrorHandling(`/statistics/estates/${estateId}`, 'GET', undefined, {
Rückgabewert fehlt
```TypeScript
this.invokeApiWithErrorHandling<RückgabeTyp>
```

2020-08-25 13:33 UTC, ffgregormueller commented on src/service/IS24PublishService/IS24PublishController.ts
> +        return await this.invokeApiWithErrorHandling(`/portals/${portalId}/projects`, 'GET');
Rückgabewert fehlt
```TypeScript
this.invokeApiWithErrorHandling<RückgabeTyp>
```

2020-08-25 13:33 UTC, ffgregormueller commented on src/service/IS24PublishService/IS24PublishController.ts
> +        return await this.invokeApiWithErrorHandling(`/OTP/estate/${estateId}/portal/${portalId}`, 'GET');
Rückgabewert fehlt
```TypeScript
this.invokeApiWithErrorHandling<RückgabeTyp>
```

2020-08-25 13:34 UTC, ffgregormueller reviewed
Typen wären super, würde aber sonst sagen, das kann gemergt werden

2020-08-27 09:26 UTC, ffjanhoeck requested changes

2020-08-27 09:26 UTC, ffjanhoeck commented on src/service/IS24PublishService/IS24Publish.Types.ts
> +    }
Bitte aus den nested Items ein Interface erstellen, sodass man das auch wiederverwenden kann und es sieht aufgeräumter aus

2020-08-31 07:26 UTC, ffjanhoeck approved these changes

2020-08-31 07:33 UTC, merged